export const roomTypes = [
  {
    _id: "00001",
    description: "Cuarto compartido 6 camas mixto",
    type: "Dorm",
    gender: "mixed",
    bathroom: "share",
    max_occupancy: 6,
    inventory: 3,
    base_rate: 12,
    currency: "USD",
    products: [
      {
        room_name: "Room 01",
        beds: [],
      },
      {
        room_name: "Room 02",
        beds: [],
      },
      {
        room_name: "Room 03",
        beds: [],
      },
    ],
  },
  {
    _id: "00002",
    description: "Cuarto compartido 4 camas femenino",
    type: "Dorm",
    gender: "female",
    bathroom: "share",
    max_occupancy: 4,
    inventory: 2,
    base_rate: 14,
    currency: "USD",
    products: [
      {
        room_name: "Room 01",
        beds: [],
      },
      {
        room_name: "Room 02",
        beds: [],
      },
    ],
  },
];

export const reservations = [
  {
    _id: "R00001",
    property_id: "P00001",
    guest_id: "G0001",
    room_type_id: "RT0001",
    booking_source: "booking.com",
    check_in_date: "2024-09-02",
    check_out_date: "2024-13-02",
    number_of_guest: 2,
    total_price: 124,
    currency: "USD",
    reservation_status: "confirm",
    payment_status: "pending",
    special_request: "late check in",
    created_At: "2024-09-01",
    updated_At: "2024-09-01",
  },
  {
    _id: "R00002",
    property_id: "P00001",
    guest_id: "G0002",
    room_type_id: "RT0001",
    booking_source: "booking.com",
    check_in_date: "2024-10-02",
    check_out_date: "2024-13-02",
    number_of_guest: 1,
    total_price: 24,
    currency: "USD",
    reservation_status: "confirm",
    payment_status: "pending",
    special_request: "late check in",
    created_At: "2024-09-01",
    updated_At: "2024-09-01",
  },
];
